wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.33.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1747779967.0
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 12
      - 41
      - 49
      - 51
      - 53
      - 55
      - 71
      - 105
      2:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 12
      - 41
      - 49
      - 51
      - 53
      - 55
      - 71
      - 105
      3:
      - 7
      - 23
      4: 3.10.12
      5: 0.16.6
      6: 4.33.2
      8:
      - 5
      13: linux-x86_64
    m:
    - 1: train/global_step
      6:
      - 3
    - 1: eval/loss
      5: 1
      6:
      - 1
    - 1: eval/accuracy
      5: 1
      6:
      - 1
    - 1: eval/runtime
      5: 1
      6:
      - 1
    - 1: eval/samples_per_second
      5: 1
      6:
      - 1
    - 1: eval/steps_per_second
      5: 1
      6:
      - 1
    - 1: train/epoch
      5: 1
      6:
      - 1
return_dict:
  desc: null
  value: true
output_hidden_states:
  desc: null
  value: false
output_attentions:
  desc: null
  value: false
torchscript:
  desc: null
  value: false
torch_dtype:
  desc: null
  value: float32
use_bfloat16:
  desc: null
  value: false
tf_legacy_loss:
  desc: null
  value: false
pruned_heads:
  desc: null
  value: {}
tie_word_embeddings:
  desc: null
  value: true
is_encoder_decoder:
  desc: null
  value: false
is_decoder:
  desc: null
  value: false
cross_attention_hidden_size:
  desc: null
  value: null
add_cross_attention:
  desc: null
  value: false
tie_encoder_decoder:
  desc: null
  value: false
max_length:
  desc: null
  value: 20
min_length:
  desc: null
  value: 0
do_sample:
  desc: null
  value: false
early_stopping:
  desc: null
  value: false
num_beams:
  desc: null
  value: 1
num_beam_groups:
  desc: null
  value: 1
diversity_penalty:
  desc: null
  value: 0.0
temperature:
  desc: null
  value: 1.0
top_k:
  desc: null
  value: 50
top_p:
  desc: null
  value: 1.0
typical_p:
  desc: null
  value: 1.0
repetition_penalty:
  desc: null
  value: 1.0
length_penalty:
  desc: null
  value: 1.0
no_repeat_ngram_size:
  desc: null
  value: 0
encoder_no_repeat_ngram_size:
  desc: null
  value: 0
bad_words_ids:
  desc: null
  value: null
num_return_sequences:
  desc: null
  value: 1
chunk_size_feed_forward:
  desc: null
  value: 0
output_scores:
  desc: null
  value: false
return_dict_in_generate:
  desc: null
  value: false
forced_bos_token_id:
  desc: null
  value: null
forced_eos_token_id:
  desc: null
  value: null
remove_invalid_values:
  desc: null
  value: false
exponential_decay_length_penalty:
  desc: null
  value: null
suppress_tokens:
  desc: null
  value: null
begin_suppress_tokens:
  desc: null
  value: null
architectures:
  desc: null
  value:
  - SwinForImageClassification
finetuning_task:
  desc: null
  value: null
id2label:
  desc: null
  value:
    '0': Albania
    '1': Andorra
    '2': Argentina
    '3': Australia
    '4': Austria
    '5': Bangladesh
    '6': Belgium
    '7': Bhutan
    '8': Bolivia
    '9': Botswana
    '10': Brazil
    '11': Bulgaria
    '12': Cambodia
    '13': Canada
    '14': Chile
    '15': Colombia
    '16': Croatia
    '17': Czechia
    '18': Denmark
    '19': Dominican Republic
    '20': Ecuador
    '21': Estonia
    '22': Eswatini
    '23': Finland
    '24': France
    '25': Germany
    '26': Ghana
    '27': Greece
    '28': Greenland
    '29': Guatemala
    '30': Hungary
    '31': Iceland
    '32': Indonesia
    '33': Ireland
    '34': Israel
    '35': Italy
    '36': Japan
    '37': Jordan
    '38': Kenya
    '39': Kyrgyzstan
    '40': Latvia
    '41': Lesotho
    '42': Lithuania
    '43': Luxembourg
    '44': Malaysia
    '45': Mexico
    '46': Mongolia
    '47': Montenegro
    '48': Netherlands
    '49': New Zealand
    '50': Nigeria
    '51': North Macedonia
    '52': Norway
    '53': Palestine
    '54': Peru
    '55': Philippines
    '56': Poland
    '57': Portugal
    '58': Romania
    '59': Russia
    '60': Senegal
    '61': Serbia
    '62': Singapore
    '63': Slovakia
    '64': Slovenia
    '65': South Africa
    '66': South Korea
    '67': Spain
    '68': Sri Lanka
    '69': Sweden
    '70': Switzerland
    '71': Taiwan
    '72': Thailand
    '73': Turkey
    '74': Ukraine
    '75': United Arab Emirates
    '76': United Kingdom
    '77': United States
    '78': Uruguay
label2id:
  desc: null
  value:
    Albania: 0
    Andorra: 1
    Argentina: 2
    Australia: 3
    Austria: 4
    Bangladesh: 5
    Belgium: 6
    Bhutan: 7
    Bolivia: 8
    Botswana: 9
    Brazil: 10
    Bulgaria: 11
    Cambodia: 12
    Canada: 13
    Chile: 14
    Colombia: 15
    Croatia: 16
    Czechia: 17
    Denmark: 18
    Dominican Republic: 19
    Ecuador: 20
    Estonia: 21
    Eswatini: 22
    Finland: 23
    France: 24
    Germany: 25
    Ghana: 26
    Greece: 27
    Greenland: 28
    Guatemala: 29
    Hungary: 30
    Iceland: 31
    Indonesia: 32
    Ireland: 33
    Israel: 34
    Italy: 35
    Japan: 36
    Jordan: 37
    Kenya: 38
    Kyrgyzstan: 39
    Latvia: 40
    Lesotho: 41
    Lithuania: 42
    Luxembourg: 43
    Malaysia: 44
    Mexico: 45
    Mongolia: 46
    Montenegro: 47
    Netherlands: 48
    New Zealand: 49
    Nigeria: 50
    North Macedonia: 51
    Norway: 52
    Palestine: 53
    Peru: 54
    Philippines: 55
    Poland: 56
    Portugal: 57
    Romania: 58
    Russia: 59
    Senegal: 60
    Serbia: 61
    Singapore: 62
    Slovakia: 63
    Slovenia: 64
    South Africa: 65
    South Korea: 66
    Spain: 67
    Sri Lanka: 68
    Sweden: 69
    Switzerland: 70
    Taiwan: 71
    Thailand: 72
    Turkey: 73
    Ukraine: 74
    United Arab Emirates: 75
    United Kingdom: 76
    United States: 77
    Uruguay: 78
tokenizer_class:
  desc: null
  value: null
prefix:
  desc: null
  value: null
bos_token_id:
  desc: null
  value: null
pad_token_id:
  desc: null
  value: null
eos_token_id:
  desc: null
  value: null
sep_token_id:
  desc: null
  value: null
decoder_start_token_id:
  desc: null
  value: null
task_specific_params:
  desc: null
  value: null
problem_type:
  desc: null
  value: null
_name_or_path:
  desc: null
  value: microsoft/swin-base-patch4-window7-224
transformers_version:
  desc: null
  value: 4.33.2
model_type:
  desc: null
  value: swin
path_norm:
  desc: null
  value: true
image_size:
  desc: null
  value: 224
patch_size:
  desc: null
  value: 4
num_channels:
  desc: null
  value: 3
embed_dim:
  desc: null
  value: 128
depths:
  desc: null
  value:
  - 2
  - 2
  - 18
  - 2
num_layers:
  desc: null
  value: 4
num_heads:
  desc: null
  value:
  - 4
  - 8
  - 16
  - 32
window_size:
  desc: null
  value: 7
mlp_ratio:
  desc: null
  value: 4.0
qkv_bias:
  desc: null
  value: true
hidden_dropout_prob:
  desc: null
  value: 0.0
attention_probs_dropout_prob:
  desc: null
  value: 0.0
drop_path_rate:
  desc: null
  value: 0.1
hidden_act:
  desc: null
  value: gelu
use_absolute_embeddings:
  desc: null
  value: false
layer_norm_eps:
  desc: null
  value: 1.0e-05
initializer_range:
  desc: null
  value: 0.02
encoder_stride:
  desc: null
  value: 32
hidden_size:
  desc: null
  value: 1024
stage_names:
  desc: null
  value:
  - stem
  - stage1
  - stage2
  - stage3
  - stage4
out_features:
  desc: null
  value:
  - stage4
out_indices:
  desc: null
  value:
  - 4
output_dir:
  desc: null
  value: /home/andreafabbricatore/rainbot/models/swin_b_finetuned_road
overwrite_output_dir:
  desc: null
  value: false
do_train:
  desc: null
  value: false
do_eval:
  desc: null
  value: true
do_predict:
  desc: null
  value: false
evaluation_strategy:
  desc: null
  value: epoch
prediction_loss_only:
  desc: null
  value: false
per_device_train_batch_size:
  desc: null
  value: 32
per_device_eval_batch_size:
  desc: null
  value: 32
per_gpu_train_batch_size:
  desc: null
  value: null
per_gpu_eval_batch_size:
  desc: null
  value: null
gradient_accumulation_steps:
  desc: null
  value: 1
eval_accumulation_steps:
  desc: null
  value: null
eval_delay:
  desc: null
  value: 0
learning_rate:
  desc: null
  value: 5.0e-05
weight_decay:
  desc: null
  value: 0.0
adam_beta1:
  desc: null
  value: 0.9
adam_beta2:
  desc: null
  value: 0.999
adam_epsilon:
  desc: null
  value: 1.0e-08
max_grad_norm:
  desc: null
  value: 1.0
num_train_epochs:
  desc: null
  value: 10
max_steps:
  desc: null
  value: -1
lr_scheduler_type:
  desc: null
  value: linear
warmup_ratio:
  desc: null
  value: 0.0
warmup_steps:
  desc: null
  value: 0
log_level:
  desc: null
  value: passive
log_level_replica:
  desc: null
  value: warning
log_on_each_node:
  desc: null
  value: true
logging_dir:
  desc: null
  value: /home/andreafabbricatore/rainbot/logs/road
logging_strategy:
  desc: null
  value: steps
logging_first_step:
  desc: null
  value: false
logging_steps:
  desc: null
  value: 500
logging_nan_inf_filter:
  desc: null
  value: true
save_strategy:
  desc: null
  value: epoch
save_steps:
  desc: null
  value: 500
save_total_limit:
  desc: null
  value: 1
save_safetensors:
  desc: null
  value: false
save_on_each_node:
  desc: null
  value: false
no_cuda:
  desc: null
  value: false
use_cpu:
  desc: null
  value: false
use_mps_device:
  desc: null
  value: false
seed:
  desc: null
  value: 42
data_seed:
  desc: null
  value: null
jit_mode_eval:
  desc: null
  value: false
use_ipex:
  desc: null
  value: false
bf16:
  desc: null
  value: false
fp16:
  desc: null
  value: false
fp16_opt_level:
  desc: null
  value: O1
half_precision_backend:
  desc: null
  value: auto
bf16_full_eval:
  desc: null
  value: false
fp16_full_eval:
  desc: null
  value: false
tf32:
  desc: null
  value: null
local_rank:
  desc: null
  value: 0
ddp_backend:
  desc: null
  value: null
tpu_num_cores:
  desc: null
  value: null
tpu_metrics_debug:
  desc: null
  value: false
debug:
  desc: null
  value: []
dataloader_drop_last:
  desc: null
  value: false
eval_steps:
  desc: null
  value: null
dataloader_num_workers:
  desc: null
  value: 0
past_index:
  desc: null
  value: -1
run_name:
  desc: null
  value: /home/andreafabbricatore/rainbot/models/swin_b_finetuned_road
disable_tqdm:
  desc: null
  value: false
remove_unused_columns:
  desc: null
  value: true
label_names:
  desc: null
  value: null
load_best_model_at_end:
  desc: null
  value: true
metric_for_best_model:
  desc: null
  value: accuracy
greater_is_better:
  desc: null
  value: true
ignore_data_skip:
  desc: null
  value: false
sharded_ddp:
  desc: null
  value: []
fsdp:
  desc: null
  value: []
fsdp_min_num_params:
  desc: null
  value: 0
fsdp_config:
  desc: null
  value:
    min_num_params: 0
    xla: false
    xla_fsdp_grad_ckpt: false
fsdp_transformer_layer_cls_to_wrap:
  desc: null
  value: null
deepspeed:
  desc: null
  value: null
label_smoothing_factor:
  desc: null
  value: 0.0
optim:
  desc: null
  value: adamw_torch
optim_args:
  desc: null
  value: null
adafactor:
  desc: null
  value: false
group_by_length:
  desc: null
  value: false
length_column_name:
  desc: null
  value: length
report_to:
  desc: null
  value:
  - tensorboard
  - wandb
ddp_find_unused_parameters:
  desc: null
  value: null
ddp_bucket_cap_mb:
  desc: null
  value: null
ddp_broadcast_buffers:
  desc: null
  value: null
dataloader_pin_memory:
  desc: null
  value: true
skip_memory_metrics:
  desc: null
  value: true
use_legacy_prediction_loop:
  desc: null
  value: false
push_to_hub:
  desc: null
  value: false
resume_from_checkpoint:
  desc: null
  value: null
hub_model_id:
  desc: null
  value: null
hub_strategy:
  desc: null
  value: every_save
hub_token:
  desc: null
  value: <HUB_TOKEN>
hub_private_repo:
  desc: null
  value: false
hub_always_push:
  desc: null
  value: false
gradient_checkpointing:
  desc: null
  value: false
include_inputs_for_metrics:
  desc: null
  value: false
fp16_backend:
  desc: null
  value: auto
push_to_hub_model_id:
  desc: null
  value: null
push_to_hub_organization:
  desc: null
  value: null
push_to_hub_token:
  desc: null
  value: <PUSH_TO_HUB_TOKEN>
mp_parameters:
  desc: null
  value: ''
auto_find_batch_size:
  desc: null
  value: false
full_determinism:
  desc: null
  value: false
torchdynamo:
  desc: null
  value: null
ray_scope:
  desc: null
  value: last
ddp_timeout:
  desc: null
  value: 1800
torch_compile:
  desc: null
  value: false
torch_compile_backend:
  desc: null
  value: null
torch_compile_mode:
  desc: null
  value: null
dispatch_batches:
  desc: null
  value: null
